name: linting
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest

    env:
      testdirs: ircbot plugins

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: 3.9

    - name: Install Python dependencies
      run: pip install isort black

    - name: Check code formatting
      run: |
        black --check --diff ${{ env.testdirs }}
        isort --profile black --check-only --diff  ${{ env.testdirs }}

  docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build docker image
        run: docker build -t urlab/lechbot .
