name: linting
on:
  push:
    branches:
      - "master"
  pull_request:
    branches:
      - "master"

jobs:
  tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        pyversion: [3.9]

    env:
      testdirs: ircbot plugins

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.pyversion }}

    - name: Install Linting dependencies
      run: pip install isort black

    - name: Install Python dependencies
      run: pip install -r requirements.txt

    - name: Check code formatting
      run: |
        black --check --diff ${{ env.testdirs }}
        isort --profile black --check-only --diff  ${{ env.testdirs }}

  docker:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2

      - name: Build container image
        uses: docker/build-push-action@v1
        with: 
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          repository: ${{ github.repository }}/lechbot
          tag_with_sha: true
          tag_with_ref: true
